"""Unit tests for src/synthgen/db_workload/.

Tests cover:
  - Document/query builders in mongo.py and postgres.py (pure functions, no live DB)
  - Rate-multiplier math via patterns.rate_multiplier
  - Validate checks for MongoDB and PostgreSQL via respx mocks

No live MongoDB or PostgreSQL connection is required.
"""

from __future__ import annotations

import random
from datetime import UTC, datetime

import pytest
import respx

from synthgen.common.patterns import rate_multiplier
from synthgen.db_workload.mongo import (
    SLOW_SCAN_INTERVAL,
    build_order_doc,
    build_slow_scan_filter,
)
from synthgen.db_workload.postgres import (
    CREATE_TABLE_SQL,
    PG_DSN_DEFAULT,
    build_insert_params,
    build_slow_scan_sql,
)
from synthsetup.validate import (
    CheckFailed,
    Ctx,
    check_mongodb_metrics,
    check_postgresql_metrics,
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

TICK = datetime(2026, 8, 11, 12, 0, 0, tzinfo=UTC)
CTX = Ctx(es_url="https://es.example.com", kibana_url="https://kb.example.com", api_key="k")

# ---------------------------------------------------------------------------
# mongo.py — build_order_doc
# ---------------------------------------------------------------------------


def test_build_order_doc_has_required_fields():
    rng = random.Random(42)
    doc = build_order_doc(rng, TICK)
    assert "order_id" in doc
    assert "customer" in doc
    assert "status" in doc
    assert "items" in doc
    assert "total" in doc
    assert "notes" in doc
    assert "created_at" in doc


def test_build_order_doc_order_id_format():
    rng = random.Random(0)
    doc = build_order_doc(rng, TICK)
    assert doc["order_id"].startswith("ORD-")
    oid = doc["order_id"][4:]
    assert oid.isdigit()
    assert 100_000 <= int(oid) <= 999_999


def test_build_order_doc_deterministic():
    doc_a = build_order_doc(random.Random(99), TICK)
    doc_b = build_order_doc(random.Random(99), TICK)
    assert doc_a == doc_b


def test_build_order_doc_status_valid():
    valid_statuses = {"pending", "confirmed", "shipped", "delivered", "cancelled"}
    for seed in range(20):
        doc = build_order_doc(random.Random(seed), TICK)
        assert doc["status"] in valid_statuses


def test_build_order_doc_items_nonempty():
    rng = random.Random(7)
    doc = build_order_doc(rng, TICK)
    assert len(doc["items"]) >= 1
    for item in doc["items"]:
        assert "sku" in item
        assert "qty" in item
        assert "price" in item


def test_build_order_doc_total_matches_items():
    rng = random.Random(13)
    doc = build_order_doc(rng, TICK)
    computed = round(sum(i["price"] * i["qty"] for i in doc["items"]), 2)
    assert doc["total"] == computed


def test_build_order_doc_notes_unindexed_prefix():
    """notes must start with 'note-' so the slow scan filter always matches."""
    for seed in range(10):
        doc = build_order_doc(random.Random(seed), TICK)
        assert doc["notes"].startswith("note-")


# ---------------------------------------------------------------------------
# mongo.py — build_slow_scan_filter
# ---------------------------------------------------------------------------


def test_build_slow_scan_filter_returns_dict():
    filt = build_slow_scan_filter()
    assert isinstance(filt, dict)
    assert "notes" in filt


def test_build_slow_scan_filter_targets_notes():
    """Filter must target the unindexed 'notes' field with a regex."""
    filt = build_slow_scan_filter()
    assert "$regex" in filt["notes"]


def test_build_slow_scan_filter_matches_notes_field():
    """The regex must match sample note values generated by build_order_doc."""
    import re

    filt = build_slow_scan_filter()
    pattern = re.compile(filt["notes"]["$regex"])
    rng = random.Random(77)
    doc = build_order_doc(rng, TICK)
    assert pattern.match(doc["notes"]), f"filter does not match notes={doc['notes']!r}"


def test_slow_scan_interval_is_300():
    assert SLOW_SCAN_INTERVAL == 300


# ---------------------------------------------------------------------------
# postgres.py — build_insert_params
# ---------------------------------------------------------------------------


def test_build_insert_params_has_required_keys():
    rng = random.Random(0)
    params = build_insert_params(rng, TICK)
    assert "order_id" in params
    assert "customer" in params
    assert "status" in params
    assert "total" in params
    assert "notes" in params
    assert "created_at" in params


def test_build_insert_params_order_id_format():
    rng = random.Random(1)
    params = build_insert_params(rng, TICK)
    assert params["order_id"].startswith("ORD-")


def test_build_insert_params_deterministic():
    a = build_insert_params(random.Random(5), TICK)
    b = build_insert_params(random.Random(5), TICK)
    assert a == b


def test_build_insert_params_total_float():
    rng = random.Random(3)
    params = build_insert_params(rng, TICK)
    assert isinstance(params["total"], float)
    assert 1.0 <= params["total"] <= 5000.0


def test_build_insert_params_notes_prefix():
    for seed in range(10):
        params = build_insert_params(random.Random(seed), TICK)
        assert params["notes"].startswith("note-")


# ---------------------------------------------------------------------------
# postgres.py — build_slow_scan_sql
# ---------------------------------------------------------------------------


def test_build_slow_scan_sql_returns_string():
    sql = build_slow_scan_sql()
    assert isinstance(sql, str)


def test_build_slow_scan_sql_targets_notes_ilike():
    sql = build_slow_scan_sql().upper()
    assert "ORDERS" in sql
    assert "NOTES" in sql
    assert "ILIKE" in sql


def test_create_table_sql_idempotent():
    assert "IF NOT EXISTS" in CREATE_TABLE_SQL
    assert "orders" in CREATE_TABLE_SQL


def test_pg_dsn_default_format():
    assert PG_DSN_DEFAULT.startswith("postgresql://")
    assert "postgres-prod" in PG_DSN_DEFAULT
    assert "5432" in PG_DSN_DEFAULT


# ---------------------------------------------------------------------------
# Rate math — rate_multiplier used by the workload loop
# ---------------------------------------------------------------------------


def test_rate_multiplier_peak_larger_than_night():
    """Peak hour (12 UTC) must produce a higher multiplier than night (03 UTC)."""
    peak = datetime(2026, 8, 11, 12, 0, 0, tzinfo=UTC)  # diurnal=1.0
    night = datetime(2026, 8, 11, 3, 0, 0, tzinfo=UTC)  # diurnal≈0.20
    m_peak = rate_multiplier(peak, "app", "db-workload")
    m_night = rate_multiplier(night, "app", "db-workload")
    assert m_peak > m_night


def test_rate_multiplier_naive_dt_raises():
    naive = datetime(2026, 8, 11, 12, 0, 0)  # no tzinfo  # noqa: DTZ001
    with pytest.raises(ValueError, match="timezone-aware"):
        rate_multiplier(naive, "app", "db-workload")


def test_base_ops_scales_with_multiplier():
    """Verify the ops-per-tick formula stays within the expected 1-20 range."""
    for hour in (0, 6, 10, 16, 23):
        t = datetime(2026, 8, 11, hour, 0, 0, tzinfo=UTC)
        mult = rate_multiplier(t, "app", "db-workload")
        base_ops = max(1, int(10 * mult))
        assert 1 <= base_ops <= 20, f"hour={hour} base_ops={base_ops} out of range"


# ---------------------------------------------------------------------------
# validate.py — check_mongodb_metrics (respx mocks)
# ---------------------------------------------------------------------------


@respx.mock
def test_mongodb_metrics_check_passes():
    respx.post("https://es.example.com/metrics-mongodb.status-default/_count").respond(
        json={"count": 120}
    )
    result = check_mongodb_metrics(CTX)
    assert "120" in result
    assert "MongoDB" in result


@respx.mock
def test_mongodb_metrics_check_zero_docs_raises():
    respx.post("https://es.example.com/metrics-mongodb.status-default/_count").respond(
        json={"count": 0}
    )
    with pytest.raises(CheckFailed, match="0 docs"):
        check_mongodb_metrics(CTX)


@respx.mock
def test_mongodb_metrics_check_404_raises():
    respx.post("https://es.example.com/metrics-mongodb.status-default/_count").respond(404)
    with pytest.raises(CheckFailed, match="does not exist"):
        check_mongodb_metrics(CTX)


# ---------------------------------------------------------------------------
# validate.py — check_postgresql_metrics (respx mocks)
# ---------------------------------------------------------------------------


@respx.mock
def test_postgresql_metrics_check_passes():
    respx.post("https://es.example.com/metrics-postgresql.database-default/_count").respond(
        json={"count": 95}
    )
    result = check_postgresql_metrics(CTX)
    assert "95" in result
    assert "PostgreSQL" in result


@respx.mock
def test_postgresql_metrics_check_zero_docs_raises():
    respx.post("https://es.example.com/metrics-postgresql.database-default/_count").respond(
        json={"count": 0}
    )
    with pytest.raises(CheckFailed, match="0 docs"):
        check_postgresql_metrics(CTX)


@respx.mock
def test_postgresql_metrics_check_404_raises():
    respx.post("https://es.example.com/metrics-postgresql.database-default/_count").respond(404)
    with pytest.raises(CheckFailed, match="does not exist"):
        check_postgresql_metrics(CTX)
