apiVersion: batch/v1
kind: Job
metadata:
  name: fleet-setup
  namespace: synthetic-network
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: fleet-setup
      restartPolicy: Never
      containers:
        - name: fleet-setup
          image: kennethfoo24/synthetic-netgen:latest
          command: ["python", "-m", "synthsetup.fleet_setup"]
          envFrom:
            - secretRef: {name: elastic-credentials}
          env:
            - name: K8S_NAMESPACE
              value: synthetic-network
