apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - databases/mongodb.yaml
  - databases/postgres.yaml
  - jobs/fleet-setup.yaml
  - elastic-agent.yaml
  - generators/syslog-gen.yaml
  - generators/syslog-ios-gen.yaml
  - generators/syslog-panw-gen.yaml
  - generators/syslog-meraki-gen.yaml
  - generators/meraki-webhook-gen.yaml
  - generators/netflow-gen.yaml
  - generators/snmpsim.yaml
  - generators/db-workload.yaml
  - logstash/logstash.yaml
